name: untitled05
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #UI
  cupertino_icons: any
  material_design_icons_flutter: any
  sizer: any
  auto_size_text: any
  bot_toast: any
  fluttertoast: any
  flutter_spinkit: any
  shimmer: any
  google_fonts: any
  carousel_slider: any
  cached_network_image: any
  animate_do: any
  progress_dialog_null_safe: any
  flutter_svg: any
  #Core
  flutter_hooks: any
  stacked: any
  stacked_services: any
  get_it: any
  rxdart: any
  #NETWORK
  dio: any
  built_value: any
  dio_http_cache: any
  dio_cache_interceptor: any
  pretty_dio_logger: any
  connectivity_plus: any
  #Utils
  intl: any
  auto_route: any
  json_annotation: any
  freezed_annotation: any
  equatable: any
  dartz: any
  logger: any
  flutter_phoenix: any
  device_preview: any
  requests_inspector: any
  open_file: any
  path: any
  path_provider: any
  shared_preferences: any
  flutter_secure_storage: any
  location: any
  #Testing
  mockito: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  built_value_generator: any
  json_serializable: any
  freezed: any

dependency_overrides:
  device_preview: 1.1.0
  flutter_hooks: 0.18.6
  stacked: 3.3.0
  stacked_services: 1.3.0
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  json_serializable: 6.6.2
  freezed: 2.3.5
  flutter_phoenix:
    git:
      url: https://github.com/mahmourad98/flutter_phoenix_plus.git
      ref: 9f91fd7
  fluttertoast:
    git:
      url: https://github.com/mahmourad98/FlutterToast-Android-S-VersionFix.git
      ref: 92c6e68

flutter:
  uses-material-design: true

  assets:
    - assets/images/bitmaps/
    - assets/images/vectors/
    - assets/lang/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 600
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900

